steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/weather-cep'
      - '.'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/weather-cep'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/weather-cep'

# Timeout for the build
timeout: '1200s'
